In [1]:
import numpy as np
import pandas as pd
import cvxpy as cp
import numpy.linalg as LA
import statsmodels.api as sm
import plotly.graph_objs as go
import matplotlib.pyplot as plt
import scipy.optimize as optimize
import statsmodels.formula.api as smf
from joblib import Parallel, delayed
from scipy.optimize import differential_evolution, NonlinearConstraint, Bounds
%matplotlib inline
%config InlineBackend.figure_format = 'svg'
plt.rcParams['figure.figsize'] = [6, 4.0]

dtafile = './dataset/Pinotti-replication/dataset.dta'
data = pd.read_stata(dtafile)

In [2]:
from auxiliary.section3_SCM import (data_prep, cvxpy_basic_solution, dynamic_graph_1, RMSPE_compare_1,
                                   table_predicted_actual, 
                                   CVXPY_iterative,
                                   scipy_weights,
                                   dynamic_graph_2,
                                   RMSPE_compare2,
                                   solution_output_SCM,
                                   SCM,
                                   data_prep_2)

In [3]:
treat_unit, treat_unit_all, control_units, control_units_all, y_treat, y_treat_all, y_control, y_control_all, Z1, Z0, X0, X1 = data_prep(data)

In [4]:
unit_identifier     = 'reg'
time_identifier     = 'year'
matching_period     = list(range(1951, 1961))
treat_unit          = 21
control_units       = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 20]
outcome_variable    = ['gdppercap']
predictor_variables = ['gdppercap', 'invrate', 'shvain', 'shvaag', 'shvams', 'shvanms', 'shskill', 'density']
reps                = 1
entire_period       = list(range(1951, 2008))

In [5]:
X0, X1, Z0, Z1 = data_prep_2(dtafile,unit_identifier,time_identifier,matching_period,treat_unit,control_units,outcome_variable,
              predictor_variables)

In [7]:
output_object = SCM(X0, X1, Z0, Z1, data,unit_identifier,time_identifier,matching_period,treat_unit,control_units,outcome_variable,predictor_variables,reps = 1)

In [9]:
solution_output_SCM(dtafile, output_object, Z0, Z1)

  Predictors     V*
0  gdppercap  0.001
1    invrate  0.227
2     shvain  0.154
3     shvaag  0.155
4     shvams  0.156
5    shvanms  0.151
6    shskill  0.154
7    density  0.002

   Region  W(V*)
0     PIE  0.000
1     VDA  0.000
2     LOM  0.000
3     TAA  0.000
4     VEN  0.000
5     FVG  0.000
6     LIG  0.000
7     EMR  0.000
8     TOS  0.000
9     UMB  0.000
10    MAR  0.000
11    LAZ  0.000
12    ABR  0.624
13    MOL  0.376
14    SAR  0.000

Optimizer Weights: [[0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.624 0.376 0.   ]]
Paper Weights:  [[0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.624 0.376 0.   ]]

RMSPE Nested:    130.14095
RMSPE Pinotti:   130.14095